In [0]:
import numpy as np

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array( [3.14, 4.2, 3])

array([3.14, 4.2 , 3.  ])

In [5]:
np.array( [1, 2, 3, 4], dtype = 'float32' )

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.array([range(i, i+3) for i in[2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full( (3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.random( (3, 4) )

array([[0.23011874, 0.93326169, 0.87915711, 0.06965018],
       [0.86548193, 0.20655464, 0.52615227, 0.54181029],
       [0.51770876, 0.57545374, 0.60259543, 0.27079903]])

In [0]:
arr_test = np.arange( 1000000 )

In [0]:
arr_test_p = list(range(1000000))

In [22]:
%time for _ in range(10): arr_result = arr_test * 2

CPU times: user 19.1 ms, sys: 15.2 ms, total: 34.3 ms
Wall time: 34.6 ms


In [23]:
%time for _ in range(10): arr_result_p = [x*2 for x in arr_test_p]

CPU times: user 863 ms, sys: 242 ms, total: 1.1 s
Wall time: 1.11 s


In [24]:
np.random.normal(0, 1, (3, 3))

array([[-0.63475218,  1.66272004, -1.43447786],
       [-0.60808414, -1.27412269, -0.64679817],
       [-0.53809676, -0.6495094 ,  1.02099872]])

In [25]:
np.random.randint(0, 10, (3, 3))

array([[2, 2, 5],
       [0, 5, 0],
       [6, 0, 6]])

In [26]:
np.eye( 3 ) #단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.empty(3)

array([1., 1., 1.])

In [28]:
np.array([1.09431908491048910141341414, 7.5, 5.4, 10.1], dtype = np.int64)

array([ 1,  7,  5, 10])

In [0]:
np.random.seed(0)

In [0]:
x1 = np.random.randint( 10, size = 6 )
x2 = np.random.randint( 10, size = (3, 4) )
x3 = np.random.randint( 10, size = (3, 4, 5), dtype = np.int64 )

In [31]:
print( 'x1 ndim : {0}'.format( x1.ndim) )
print( 'x1 shape : {0}'.format( x1.shape))
print( 'x1 size : {0}'.format( x1.size))
print( 'x1 dtype : {0}'.format( x1.dtype))
print( 'x1 itemsize : {0}'.format( x1.itemsize))
print( 'x1 nbytes : {0}'.format( x1.nbytes))

x1 ndim : 1
x1 shape : (6,)
x1 size : 6
x1 dtype : int64
x1 itemsize : 8
x1 nbytes : 48


In [33]:
print( 'x2 ndim : {0}'.format( x2.ndim) )
print( 'x2 shape : {0}'.format( x2.shape))
print( 'x2 size : {0}'.format( x2.size))
print( 'x2 dtype : {0}'.format( x2.dtype))
print( 'x2 itemsize : {0}'.format( x2.itemsize))
print( 'x2 nbytes : {0}'.format( x2.nbytes))

x2 ndim : 2
x2 shape : (3, 4)
x2 size : 12
x2 dtype : int64
x2 itemsize : 8
x2 nbytes : 96


In [38]:
print( 'x3 ndim : {0}'.format( x3.ndim) )        # 차원
print( 'x3 shape : {0}'.format( x3.shape))       # 3 * 4 * 5
print( 'x3 size : {0}'.format( x3.size))         # 데이터 크기
print( 'x3 dtype : {0}'.format( x3.dtype))       # 타입
print( 'x3 itemsize : {0}'.format( x3.itemsize)) # 배열 요소의 데이터 크기 4bytes
print( 'x3 nbytes : {0}'.format( x3.nbytes))     # size * itemsize

x3 ndim : 3
x3 shape : (3, 4, 5)
x3 size : 60
x3 dtype : int64
x3 itemsize : 8
x3 nbytes : 480


In [0]:
x = np.array([8, 5, 3, 0])

In [0]:
x2_copy = x1.copy()

In [43]:
x2_copy.dtype

dtype('int64')

In [44]:
x2_copy.shape

(6,)

In [0]:
x2_copy[2] = 100

In [47]:
x2_copy

array([  4,   3, 100,   4,   8,   4])