In [1]:
import csv
import numpy as np

In [2]:
# 전국 주요 상권 정보

In [3]:
dates = []
areas = []
cities = []
male_10 = []
male_20 = []
male_30 = []
male_40 = []
male_50 = []
female_10 = []
female_20 = []
female_30 = []
female_40 = []
female_50 = []

index = 0
with open( 'korea_floating_population_data.csv', 'r' ) as f:
    reader = csv.reader( f )
    for row in reader:
        if index != 0:
            dates.append( row[ 3 ] )
            areas.append( row[ 7 ]  )
            cities.append( row[ 7 ].split()[ 0 ] )
            male_10.append( int( row[ 9 ] ) )
            male_20.append( int( row[ 10 ] ) )
            male_30.append( int( row[ 11 ] ) )
            male_40.append( int( row[ 12 ] ) )
            male_50.append( int( row[ 13 ] ) )
            female_10.append( int( row[ 14 ] ) )
            female_20.append( int( row[ 15 ] ) )
            female_30.append( int( row[ 16 ] ) )
            female_40.append( int( row[ 17 ] ) )
            female_50.append( int( row[ 18 ] ) )
        index += 1

print( dates )
print()
print( areas )
print()
print( cities )
print()
print( male_10 )
print()
print( female_10 )

['2010-06-21', '2010-06-21', '2010-06-20', '2010-06-20', '2010-06-21', '2010-06-21', '2010-06-20', '2010-06-20', '2010-06-04', '2010-06-04', '2010-06-05', '2010-06-05', '2010-06-24', '2010-06-24', '2010-06-26', '2010-06-26', '2010-06-24', '2010-06-24', '2010-06-26', '2010-06-26', '2010-06-27', '2010-06-27', '2010-06-27', '2010-06-27', '2010-06-28', '2010-06-28', '2010-06-26', '2010-06-26', '2010-06-28', '2010-06-28', '2010-06-26', '2010-06-26', '2010-06-29', '2010-06-29', '2010-06-27', '2010-06-27', '2010-06-29', '2010-06-29', '2010-06-27', '2010-06-27', '2010-06-09', '2010-06-09', '2010-06-12', '2010-06-12', '2010-06-09', '2010-06-09', '2010-06-12', '2010-06-12', '2010-07-01', '2010-07-01', '2010-07-03', '2010-07-03', '2010-07-01', '2010-07-01', '2010-07-03', '2010-07-03', '2010-07-15', '2010-07-15', '2010-07-03', '2010-07-03', '2010-07-15', '2010-07-15', '2010-07-03', '2010-07-03', '2010-07-05', '2010-07-05', '2010-07-04', '2010-07-04', '2010-07-05', '2010-07-05', '2010-07-04', '2010

In [4]:
date_array = np.array( dates )
area_array = np.array( areas )
city_array = np.array( cities )
male_array = np.array( [ male_10, male_20, male_30, male_40, male_50 ] )
male_array = male_array.T
female_array = np.array( [ female_10, female_20, female_30, female_40, female_50 ] )
female_array = female_array.T

In [5]:
date_array

array(['2010-06-21', '2010-06-21', '2010-06-20', ..., '2010-07-07',
       '2010-07-10', '2010-07-10'], dtype='<U10')

In [6]:
area_array

array(['대전광역시 서구 월평동', '대전광역시 서구 월평동', '대전광역시 서구 월평동', ..., '경기도 화성시 장안면',
       '경기도 화성시 장안면', '경기도 화성시 장안면'], dtype='<U20')

In [7]:
area_array.shape

(23245,)

In [8]:
city_array

array(['대전광역시', '대전광역시', '대전광역시', ..., '경기도', '경기도', '경기도'], dtype='<U7')

In [9]:
male_array

array([[ 2, 24, 68, 50, 31],
       [19, 44, 28, 33, 21],
       [13, 33, 34, 61, 55],
       ...,
       [25, 13, 29, 23, 55],
       [12, 15, 35, 31, 45],
       [15, 20, 32, 27, 42]])

In [10]:
female_array

array([[ 4, 37, 64, 44, 26],
       [14, 56, 49, 43, 18],
       [13, 32, 29, 28, 12],
       ...,
       [31, 17, 37, 19, 45],
       [10, 12, 31, 25, 37],
       [12, 18, 29, 31, 43]])

In [11]:
male_array.shape

(23245, 5)

In [12]:
female_array.shape

(23245, 5)

In [13]:
city_mask = city_array == '대전광역시'

In [14]:
male_array[ city_mask ]

array([[ 2, 24, 68, 50, 31],
       [19, 44, 28, 33, 21],
       [13, 33, 34, 61, 55],
       ...,
       [84, 76, 64, 49, 38],
       [81, 46, 39, 28, 17],
       [94, 75, 42, 24, 29]])

In [15]:
female_array[ city_mask ]

array([[  4,  37,  64,  44,  26],
       [ 14,  56,  49,  43,  18],
       [ 13,  32,  29,  28,  12],
       ...,
       [ 95,  96, 169,  92,  76],
       [ 55,  70,  83,  41,  19],
       [ 57,  75,  82,  64,  37]])

In [16]:
male_array[ city_mask ].shape

(872, 5)

In [17]:
female_array[ city_mask ].shape

(872, 5)

In [17]:
male_total = np.sum( male_array[ city_mask ] )
female_total = np.sum( female_array[ city_mask ] )

total = male_total + female_total
print( '대전광역시 주요 상권 방문자 수                   : {0}\n'.format( total ) )

male_age_total = np.sum( male_array[ city_mask ], axis = 0 )
print( '대전광역시 주요 상권 남자 총 방문자 수           : {0}'.format( male_total ) )
print( '대전광역시 주요 상권 남자 방문자 비율            : {0:.2f}%\n'.format( male_total / total * 100 ) )
print( '대전광역시 주요 상권 남자 10대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( male_age_total[ 0 ], 
                                                                                   male_age_total[ 0 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 남자 20대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( male_age_total[ 1 ],
                                                                                   male_age_total[ 1 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 남자 30대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( male_age_total[ 2 ],
                                                                                   male_age_total[ 2 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 남자 40대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( male_age_total[ 3 ], 
                                                                                   male_age_total[ 3 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 남자 50대 방문자 수( 비율 ) : {0}( {1:.2f} )\n'.format( male_age_total[ 4 ], 
                                                                                     male_age_total[ 4 ] / male_total * 100 ) )


female_age_total = np.sum( female_array[ city_mask ], axis = 0 )
print( '대전광역시 주요 상권 여자 총 방문자 수           : {0}'.format( female_total ) )
print( '대전광역시 주요 상권 여자 방문자 비율            : {0:.2f}%\n'.format( female_total / total * 100 ) )
print( '대전광역시 주요 상권 여자 10대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( female_age_total[ 0 ], 
                                                                                   female_age_total[ 0 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 여자 20대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( female_age_total[ 1 ],
                                                                                   female_age_total[ 1 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 여자 30대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( female_age_total[ 2 ],
                                                                                   female_age_total[ 2 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 여자 40대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( female_age_total[ 3 ], 
                                                                                   female_age_total[ 3 ] / male_total * 100 ) )
print( '대전광역시 주요 상권 여자 50대 방문자 수( 비율 ) : {0}( {1:.2f} )'.format( female_age_total[ 4 ], 
                                                                                   female_age_total[ 4 ] / male_total * 100 ) )

대전광역시 주요 상권 방문자 수                   : 429999

대전광역시 주요 상권 남자 총 방문자 수           : 203650
대전광역시 주요 상권 남자 방문자 비율            : 47.36%

대전광역시 주요 상권 남자 10대 방문자 수( 비율 ) : 32728( 16.07 )
대전광역시 주요 상권 남자 20대 방문자 수( 비율 ) : 55972( 27.48 )
대전광역시 주요 상권 남자 30대 방문자 수( 비율 ) : 45670( 22.43 )
대전광역시 주요 상권 남자 40대 방문자 수( 비율 ) : 40072( 19.68 )
대전광역시 주요 상권 남자 50대 방문자 수( 비율 ) : 29208( 14.34 )

대전광역시 주요 상권 여자 총 방문자 수           : 226349
대전광역시 주요 상권 여자 방문자 비율            : 52.64%

대전광역시 주요 상권 여자 10대 방문자 수( 비율 ) : 34391( 16.89 )
대전광역시 주요 상권 여자 20대 방문자 수( 비율 ) : 62925( 30.90 )
대전광역시 주요 상권 여자 30대 방문자 수( 비율 ) : 55040( 27.03 )
대전광역시 주요 상권 여자 40대 방문자 수( 비율 ) : 42620( 20.93 )
대전광역시 주요 상권 여자 50대 방문자 수( 비율 ) : 31373( 15.41 )
