In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [1]:
import numpy as np
import csv

# 미국 대통령 키에 대한 분석

In [3]:
dataset = []
with open('president_heights.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
      dataset.append(row)

In [4]:
df = np.array(dataset)

In [5]:
height = np.array(df[1:,2], dtype=int)

In [6]:
height

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185])

In [7]:
print('역대 미국대통령 수는 : {}'.format(len(height)))
print('역대 미국대통령들의 키 중 최솟값은 : {}'.format(np.min(height)))
print('역대 미국대통령들의 키 중 최댓값은 : {}'.format(np.max(height)))
print('역대 미국대통령들의 키 중 평균은 : {}'.format(int(np.mean(height))))

역대 미국대통령 수는 : 42
역대 미국대통령들의 키 중 최솟값은 : 163
역대 미국대통령들의 키 중 최댓값은 : 193
역대 미국대통령들의 키 중 평균은 : 179


# 시애틀 강수 데이터

In [10]:
dataset = []
with open('Seattle2014.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
      dataset.append(row)

In [11]:
df = np.array(dataset)

In [12]:
prcp = np.array(df[1:,3], dtype = int)

In [13]:
prcp

array([  0,  41,  15,   0,   0,   3, 122,  97,  58,  43, 213,  15,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   5,   0,   0,   0,   0,
         0,  89, 216,   0,  23,  20,   0,   0,   0,   0,   0,   0,  51,
         5, 183, 170,  46,  18,  94, 117, 264, 145, 152,  10,  30,  28,
        25,  61, 130,   3,   0,   0,   0,   5, 191, 107, 165, 467,  30,
         0, 323,  43, 188,   0,   0,   5,  69,  81, 277,   3,   0,   5,
         0,   0,   0,   0,   0,  41,  36,   3, 221, 140,   0,   0,   0,
         0,  25,   0,  46,   0,   0,  46,   0,   0,   0,   0,   0,   0,
         5, 109, 185,   0, 137,   0,  51, 142,  89, 124,   0,  33,  69,
         0,   0,   0,   0,   0, 333, 160,  51,   0,   0, 137,  20,   5,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38,
         0,  56,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  18,  64,   0,   5,  36,  13,   0,
         8,   3,   0,   0,   0,   0,   0,   0,  18,  23,   0,   

In [14]:
print('Seattle의 2014년 누적 강수량은 : {}'.format(np.sum(prcp)))
print('Seattle의 2014년 일 최대 강수량은 : {}'.format(np.max(prcp)))
print('Seattle의 2014년 강수량 평균은 : {}'.format(int(np.mean(prcp))))
print('Seattle의 2014년 강수량 분산은 : {}'.format(int(np.var(prcp))))
print('Seattle의 2014년 강수량 표준편차는 : {}'.format(int(np.std(prcp))))

Seattle의 2014년 누적 강수량은 : 12328
Seattle의 2014년 일 최대 강수량은 : 467
Seattle의 2014년 강수량 평균은 : 33
Seattle의 2014년 강수량 분산은 : 4586
Seattle의 2014년 강수량 표준편차는 : 67


In [15]:
#비온 날만 따로 구분
rain_prcp = prcp[prcp>0]

In [16]:
print('Seattle의 2014년 강수 일은 : {}'.format(int(np.mean(rain_prcp))))
print('Seattle의 2014년 강수 일 중, 강수량 평균은 : {}'.format(int(np.mean(rain_prcp))))
print('Seattle의 2014년 강수 일 중, 강수량 분산은 : {}'.format(int(np.var(rain_prcp))))
print('Seattle의 2014년 강수 일 중, 강수량 표준편차는 : {}'.format(int(np.std(rain_prcp))))

Seattle의 2014년 강수 일은 : 82
Seattle의 2014년 강수 일 중, 강수량 평균은 : 82
Seattle의 2014년 강수 일 중, 강수량 분산은 : 7181
Seattle의 2014년 강수 일 중, 강수량 표준편차는 : 84


# 한국 상권분석

In [34]:
dataset = []
with open('korea_floating_population_data.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
      dataset.append(row)

In [35]:
df = np.array(dataset)

In [33]:
df

array([['조사번호', '조사지역', '주구분', ..., '여자30대', '여자40대', '여자50대'],
       ['2544', '신촌네거리 계룡건설 사옥 농협 앞', '주중', ..., '64', '44', '26'],
       ['2544', '신촌네거리 계룡건설 사옥 농협 앞', '주중', ..., '49', '43', '18'],
       ...,
       ['8644', '조암삼거리', '주중', ..., '37', '19', '45'],
       ['8644', '조암삼거리', '주말', ..., '31', '25', '37'],
       ['8644', '조암삼거리', '주말', ..., '29', '31', '43']], dtype='<U36')

In [20]:
df[:3,]

array([['조사번호', '조사지역', '주구분', '조사일자', '시간대', 'X좌표', 'Y좌표', '행정구역명',
        '날씨', '남자10대', '남자20대', '남자30대', '남자40대', '남자50대', '여자10대',
        '여자20대', '여자30대', '여자40대', '여자50대'],
       ['2544', '신촌네거리 계룡건설 사옥 농협 앞', '주중', '2010-06-21', '12시~13시까지',
        '343099', '417482', '대전광역시 서구 월평동', '맑음', '2', '24', '68', '50',
        '31', '4', '37', '64', '44', '26'],
       ['2544', '신촌네거리 계룡건설 사옥 농협 앞', '주중', '2010-06-21', '19시~20시까지',
        '343099', '417482', '대전광역시 서구 월평동', '맑음', '19', '44', '28', '33',
        '21', '14', '56', '49', '43', '18']], dtype='<U36')

In [21]:
my = df[df[:,7] == "대전광역시 서구 괴정동"]

In [22]:
var_name = df[0,:]

In [23]:
var_name

array(['조사번호', '조사지역', '주구분', '조사일자', '시간대', 'X좌표', 'Y좌표', '행정구역명', '날씨',
       '남자10대', '남자20대', '남자30대', '남자40대', '남자50대', '여자10대', '여자20대',
       '여자30대', '여자40대', '여자50대'], dtype='<U36')

In [24]:
my

array([['4102', 'B지역(SKY편의점 앞)', '주중', '2010-06-21', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음', '0', '12', '24', '36',
        '0', '6', '30', '16', '34', '4'],
       ['4102', 'B지역(SKY편의점 앞)', '주중', '2010-06-21', '19시~20시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음', '28', '16', '54', '44',
        '0', '24', '12', '28', '34', '18'],
       ['4102', 'B지역(SKY편의점 앞)', '주말', '2010-06-26', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음', '60', '12', '8', '30',
        '0', '8', '14', '10', '24', '12'],
       ['4102', 'B지역(SKY편의점 앞)', '주말', '2010-06-26', '19시~20시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음', '46', '12', '36', '42',
        '0', '0', '20', '24', '40', '12'],
       ['8481', 'B지역(SKY편의점 앞)', '주중', '2010-11-08', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음', '12', '42', '27', '51',
        '0', '0', '48', '12', '40', '2'],
       ['8481', 'B지역(SKY편의점 앞)', '주중', '2010-11-08', '19시~20시까지',
        '344304', '415

In [25]:
my_str = np.array(my[:,:9], dtype=str)
my_str

array([['4102', 'B지역(SKY편의점 앞)', '주중', '2010-06-21', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['4102', 'B지역(SKY편의점 앞)', '주중', '2010-06-21', '19시~20시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['4102', 'B지역(SKY편의점 앞)', '주말', '2010-06-26', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['4102', 'B지역(SKY편의점 앞)', '주말', '2010-06-26', '19시~20시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['8481', 'B지역(SKY편의점 앞)', '주중', '2010-11-08', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['8481', 'B지역(SKY편의점 앞)', '주중', '2010-11-08', '19시~20시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['8481', 'B지역(SKY편의점 앞)', '주말', '2010-11-13', '12시~13시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음'],
       ['8481', 'B지역(SKY편의점 앞)', '주말', '2010-11-13', '19시~20시까지',
        '344304', '415843', '대전광역시 서구 괴정동', '맑음']], dtype='<U36')

In [26]:
my_value = np.array(my[:,9:], dtype=int)
my_value

array([[ 0, 12, 24, 36,  0,  6, 30, 16, 34,  4],
       [28, 16, 54, 44,  0, 24, 12, 28, 34, 18],
       [60, 12,  8, 30,  0,  8, 14, 10, 24, 12],
       [46, 12, 36, 42,  0,  0, 20, 24, 40, 12],
       [12, 42, 27, 51,  0,  0, 48, 12, 40,  2],
       [51, 66, 42, 51,  0, 18, 42, 18, 38,  7],
       [63, 39, 39, 30,  0, 33, 24, 24, 50,  7],
       [45, 36, 24, 42,  0, 18, 12, 21, 30,  6]])

In [27]:
my_max = my_value.max(axis=1).reshape(len(my_value),1)
my_max

array([[36],
       [54],
       [60],
       [46],
       [51],
       [66],
       [63],
       [45]])

In [28]:
chk = 0
gender_age = []
for i in range(len(my_value)):
  for j in range(len(my_value[0])):
    if my_value[i, j]==my_max[i]:
      chk = j
      break;
  gender_age.append(var_name[10+chk])
print(gender_age)

['남자50대', '남자40대', '남자20대', '남자20대', '남자50대', '남자30대', '남자20대', '남자20대']


In [29]:
print('{0}의 특정 날짜의 요일, 날씨의 시간대에 따른 주 행인 분석결과'.format(my_str[0,7]))
print("================================================================================")
for i in range(len(my_str)):
  print(my_str[i,7], my_str[i,3], my_str[i,2], my_str[i,8], my_str[i,4], end = '')
  print(' 주 행인은 {0}이다.'.format(gender_age[i]))
print("================================================================================")

대전광역시 서구 괴정동의 특정 날짜의 요일, 날씨의 시간대에 따른 주 행인 분석결과
대전광역시 서구 괴정동 2010-06-21 주중 맑음 12시~13시까지 주 행인은 남자50대이다.
대전광역시 서구 괴정동 2010-06-21 주중 맑음 19시~20시까지 주 행인은 남자40대이다.
대전광역시 서구 괴정동 2010-06-26 주말 맑음 12시~13시까지 주 행인은 남자20대이다.
대전광역시 서구 괴정동 2010-06-26 주말 맑음 19시~20시까지 주 행인은 남자20대이다.
대전광역시 서구 괴정동 2010-11-08 주중 맑음 12시~13시까지 주 행인은 남자50대이다.
대전광역시 서구 괴정동 2010-11-08 주중 맑음 19시~20시까지 주 행인은 남자30대이다.
대전광역시 서구 괴정동 2010-11-13 주말 맑음 12시~13시까지 주 행인은 남자20대이다.
대전광역시 서구 괴정동 2010-11-13 주말 맑음 19시~20시까지 주 행인은 남자20대이다.
